config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#welcome'

  resources :products do
    resources :reviews, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost ,products.origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}
  scope :made, -> { where(origin: "United States" )}

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product



  validates :author, :presence => true
  validates :content_body, length: {maximum: 250}
  validates :content_body, length: {minimum: 50}
  validates_inclusion_of :rating, :in => 1..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def welcome
    @products = Product.all
  end
  def show
      @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new (product_params)
    if @product.save
      flash[:notice] = "Product has been added."
      redirect_to products_path(@product)
    else
      render :new
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end
  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :cost %>
  <br>
  <%= f.number_field :cost, class: :text_field, step: :any %>
  <br>
  <%= f.label :origin %>
  <br>
  <%= f.text_field :origin %>
  <br>
  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
      <div class="well">
        <br><br><br>
      </div>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h3>
<div class="well">
<%= link_to "All Products", products_path %>
</div>
</h3>
<h1>Edit product</h1>
<br>
<br>
<hr>
<%= render "layouts/errors", :object => @product %>

<%= render "layouts/form" %>

app/views/products/index.html.erb
<h3>
  <div class="well">
    <%= link_to "Welcome", "/" %>
    ||
    <%= link_to "New Product", new_product_path %>
  </div>
</h3>

<h1>Products</h1>
<h3>



  <ul>
    <% @products.each do |product| %>
      <div class="panel">
      <li><%=link_to product.name, product_path(product) %></li>
      </div>
    <% end %>
  </ul>

</h3>

app/views/products/new.html.erb
<div class="well">
<h3>
<%= link_to "All Products", products_path %>
</h3>
</div>

<h1>New product</h1>
<br>
<br>
<hr>
<%= render "layouts/errors", :object => @product %>

<%= render "layouts/form" %>

app/views/products/show.html.erb
<% content_for(:title, "Products | Mario's Foods") %>
<h3>
<div class="well">
<%= link_to "Welcome", "/" %> ||
<%= link_to "Return to products", products_path %>

</div>
</h3>

<h1><%= @product.name %></h1>
<br>
<h1>$<%= @product.cost %></h1>
<br>
<h1><%= @product.origin %></h1>
<br>
<hr>
<br>


<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <ul>
    <% @product.reviews.each do |review| %>
    <div class="well">


      <li>
        <h3>Author:</h3> <h4> <%= review.author %> </h4>
        <h4> <%= review.content_body %> </h4>


        <h3>Rating:</h3> <h4><%= review.rating %></h4>
        <br>
        <%= link_to "Delete", product_review_path(@product, review),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    </div>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>


<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<br>
<hr>
<h3>

app/views/products/welcome.html.erb
<div class="well">
<h3>

<%= link_to "All Products", products_path %> ||
<%= link_to "New Product", new_product_path %>
</h3>
</div>

<h1>Welcome to Mario's Foods</h1>
<h3>Every Family Has A Story. This Is Ours.
<br>
<br>
It was my father’s love and passion for food that brought Mario’s to life in 1944. With a worn notebook of cherished sausage recipes preserved for generations by our family in southern Italy, Dad made it his mission to deliver products of exceptional quality, flavor and value to the customers of my grandfather’s grocery store.<br> His mission – and our commitment to fulfilling it – are at the heart of our business to this day.
<br>
<br>
Through years of hard work and perseverance, Mario’s earned the respect of our industry and –more importantly – the trust of our customers. While much has changed since 1944, our passion for food and our business philosophy remain the same: Exceed our customers’ expectations by bringing them unmatched value and unparalleled service. We are dedicated to the communities we serve, committed to sustainable business practices, and focused on aligning our products and services to meet the specific needs of our customers.
<br>
At Mario’s, we take pride in treating every customer the same – from the smallest operator to the largest restaurant chain. We look forward to “Building on a Tradition of Service” with you as a valued partner.
<br>
<br>
Welcome to the Mario family,
<br>
Mario Mario
<br>
President</h3>
<br>
<hr>
<br>
<ul>
  <h4>Here is our three most recently added products:
  <% @products.three_most_recent.each do |product| %>
    <li><%=link_to product.name, product_path(product) %></li>
  <% end %>
  <br>
  Here is our product with the most reviews:
  <%  @products.most_reviews.each do |product| %>
    <li><%=link_to product.name, product_path(product) %></li>
  <% end %>
  <br>
  Here is a list of products made in the USA:
  <%  @products.made.each do |product| %>
    <li><%=link_to product.name, product_path(product) %></li>
  <% end %>

</ul>
</h4>
<br>
<hr>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :autor %>
  <br>
  <%= f.text_field :author %>
  <br>
  <%= f.label :content_body %>
  <br>
  <%= f.text_field :content_body %>
  <p tyle="font-size: 11px">Must contain between 50-250 characters.</p>
  <br>
  <%= f.label :rating %>
  <br>
  <%= f.select :rating, options_for_select(0..5) %>
  <br>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<div class="well">
<%= link_to "All Products", products_path %>
</div>
<h1>New review for <%= @product.name %></h1>

<%= render 'form' %>